Improve php 7.3 container to working state

diff --git a/containers/php-fpm/Dockerfile b/containers/php-fpm/Dockerfile
--- a/containers/php-fpm/Dockerfile
+++ b/containers/php-fpm/Dockerfile
@@ -1,10 +1,45 @@
-FROM phpdockerio/php73-fpm:latest
+FROM php:7.3-fpm
 
 COPY xdebug.ini /tmp/xdebug.ini
 
-RUN apt-get update \
-    && apt-get -y --no-install-recommends install php7.3-mysql php-xdebug php7.3-bcmath php7.3-gd php7.3-imap php7.3-soap \
-    && mv /tmp/xdebug.ini /etc/php/7.3/fpm/conf.d/20-xdebug.ini \
-    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
+ARG HOST_USER_ID
+ARG HOST_USER_NAME
+ARG HOST_GROUP_ID
+ARG HOST_GROUP_NAME
+
+ARG RUNTIME_PACKAGE_DEPS="ssmtp libfreetype6 libjpeg62-turbo unzip git mysql-client sudo rsync liblz4-tool"
+ARG BUILD_PACKAGE_DEPS="libcurl4-openssl-dev libjpeg-dev libpng-dev libxml2-dev libzip-dev"
+ARG PHP_EXT_DEPS="curl json xml mbstring zip bcmath soap pdo_mysql gd mysqli"
+ARG PHP_MEMORY_LIMIT="-1"
+
+# install dependencies and cleanup (needs to be one step, as else it will cache in the laver)
+RUN apt-get update -y \
+    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
+        $RUNTIME_PACKAGE_DEPS \
+        $BUILD_PACKAGE_DEPS \
+    && docker-php-ext-configure gd --with-jpeg-dir=/usr/local/ \
+    && docker-php-ext-install -j$(nproc) $PHP_EXT_DEPS \
+    && pecl install xdebug \
+    && mv /tmp/xdebug.ini /usr/local/etc/php/conf.d/20-xdebug.ini \
+    && apt-get clean \
+    && apt-get autoremove -y \
+    && apt-get purge -y --auto-remove $BUILD_PACKAGE_DEPS \
+    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
+
+
+# set sendmail for php to ssmtp
+RUN echo "sendmail_path=/usr/sbin/ssmtp -t" > /usr/local/etc/php/conf.d/php-sendmail.ini
+
+# remove memory limit
+RUN echo "memory_limit = $PHP_MEMORY_LIMIT" > /usr/local/etc/php/conf.d/memory-limit-php.ini
+
+# install latest composer
+RUN curl --silent --show-error https://getcomposer.org/installer | php && \
+    mv /var/www/html/composer.phar /usr/local/bin/composer
+
+RUN groupadd -f -g $HOST_GROUP_ID $HOST_GROUP_NAME && \
+    useradd -m -d /home/$HOST_USER_NAME -s /bin/bash -g $HOST_GROUP_ID -u $HOST_USER_ID $HOST_USER_NAME || true && \
+    echo "$HOST_USER_NAME  ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
+    chown -R $HOST_USER_NAME.$HOST_GROUP_NAME /var/www/
 
 WORKDIR /var/www/
